# Generated by Django 2.2.6 on 2019-11-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
